services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    depends_on:
      - db
    expose:
      - "3000"
    restart: always

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  mysql_data:
  certs:
  certbot-www:
