services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    depends_on:
      - db
    expose:
      - "3000"
    restart: always

  # front サービスは「ビルド用」として使い切ったら不要
  # 本番では nginx が dist を含むイメージを持つべきなので削除
  # front:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - back
  #   restart: no

  nginx:
    build:
      context: ./frontend  # frontend の Dockerfile で nginx 化済みイメージにする
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back
    restart: always

volumes:
  mysql_data:
