services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    depends_on:
      - db
    expose:
      - "3000"
    restart: always

  # 本番は nginx がフロントを配信（./frontend の Dockerfile は nginx ベース想定）
  nginx:
    build:
      context: ./frontend    # dist を含む nginx イメージをここで作る想定
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/etc/letsencrypt                     # ← 証明書置き場
      - certbot-www:/var/www/certbot               # ← ACME http-01 用webroot
    restart: always

  # 証明書の取得/更新に使う（常駐させない）
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: /bin/sh

volumes:
  mysql_data:
  certs:
  certbot-www:
